<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Atata.AspNetCore</RootNamespace>
    <Description>
C#/.NET library that adds ASP.NET Core 9.0 sessions to Atata using WebApplicationFactory.

Atata.AspNetCore.v9 on GitHub: https://github.com/atata-framework/atata-aspnetcore
Atata Framework documentation: https://atata.io/

The package targets .NET 9.0.
    </Description>
    <RepositoryUrl>https://github.com/atata-framework/atata-aspnetcore</RepositoryUrl>
    <PackageId>Atata.AspNetCore.v9</PackageId>
    <PackageTags>atata automation testing test aspnetcore aspnetcoremvc aspnetcoremvctesting</PackageTags>
    <PackageReleaseNotes>Changelog: https://github.com/atata-framework/atata-aspnetcore/blob/main/CHANGELOG.v9.md</PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/atata-framework/atata-aspnetcore</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Atata" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" Version="9.10.0" />
  </ItemGroup>

</Project>
